# Generated by Django 5.2.5 on 2025-11-30 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_reserva_hora_fin_reserva_codigo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='abre_feriados',
            field=models.BooleanField(default=True, verbose_name='¿Abre feriados?'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='hora_apertura',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de Apertura'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='hora_cierre',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Hora de Cierre'),
        ),
    ]
