# Generated by Django 5.2.5 on 2025-11-30 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cancha_abre_feriados_cancha_hora_apertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canchas_propias', to=settings.AUTH_USER_MODEL, verbose_name='Dueño de la Cancha'),
        ),
    ]
